permalink: /:categories/:title.html
url: "http://cdiegosr.github.io"
full_name: "Carlos Diego"
first_name: "Carlos Diego"
last_name: "Rodrigues"
blog_title: "And about "
author_img_name_path: "/images/users/cdiego-baiahacker_120.jpg"
disqus_shortname: "cdiegosr"
copyright_year: "2018"
google_analytics_code: ""
aboutme: "An activist"
twitter: "diegoitu"
github: "cdiegosr"
facebook: "cdiegosr"
linkined_url: "https://linkedin.com/n/cdiegosr"
