permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: Carlos Diego
description: Coisas do caipira ativista
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true